// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `Slices.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package slices;

public interface DiscoverHelloPrx extends Ice.ObjectPrx
{
    public String getInstanceId();

    public String getInstanceId(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getInstanceId();

    public Ice.AsyncResult begin_getInstanceId(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getInstanceId(Ice.Callback __cb);

    public Ice.AsyncResult begin_getInstanceId(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getInstanceId(Callback_DiscoverHello_getInstanceId __cb);

    public Ice.AsyncResult begin_getInstanceId(java.util.Map<String, String> __ctx, Callback_DiscoverHello_getInstanceId __cb);

    public String end_getInstanceId(Ice.AsyncResult __result);

    public AgentEntity[] getAgents();

    public AgentEntity[] getAgents(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getAgents();

    public Ice.AsyncResult begin_getAgents(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getAgents(Ice.Callback __cb);

    public Ice.AsyncResult begin_getAgents(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getAgents(Callback_DiscoverHello_getAgents __cb);

    public Ice.AsyncResult begin_getAgents(java.util.Map<String, String> __ctx, Callback_DiscoverHello_getAgents __cb);

    public AgentEntity[] end_getAgents(Ice.AsyncResult __result);
}
