// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `Slices.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package slices;

public final class DiscoverHelloPrxHelper extends Ice.ObjectPrxHelperBase implements DiscoverHelloPrx
{
    private static final String __getAgents_name = "getAgents";

    public AgentEntity[] getAgents()
    {
        return getAgents(null, false);
    }

    public AgentEntity[] getAgents(java.util.Map<String, String> __ctx)
    {
        return getAgents(__ctx, true);
    }

    private AgentEntity[] getAgents(java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "getAgents", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("getAgents");
                    __delBase = __getDelegate(false);
                    _DiscoverHelloDel __del = (_DiscoverHelloDel)__delBase;
                    return __del.getAgents(__ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_getAgents()
    {
        return begin_getAgents(null, false, null);
    }

    public Ice.AsyncResult begin_getAgents(java.util.Map<String, String> __ctx)
    {
        return begin_getAgents(__ctx, true, null);
    }

    public Ice.AsyncResult begin_getAgents(Ice.Callback __cb)
    {
        return begin_getAgents(null, false, __cb);
    }

    public Ice.AsyncResult begin_getAgents(java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_getAgents(__ctx, true, __cb);
    }

    public Ice.AsyncResult begin_getAgents(Callback_DiscoverHello_getAgents __cb)
    {
        return begin_getAgents(null, false, __cb);
    }

    public Ice.AsyncResult begin_getAgents(java.util.Map<String, String> __ctx, Callback_DiscoverHello_getAgents __cb)
    {
        return begin_getAgents(__ctx, true, __cb);
    }

    private Ice.AsyncResult begin_getAgents(java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__getAgents_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __getAgents_name, __cb);
        try
        {
            __result.__prepare(__getAgents_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            __result.__writeEmptyParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public AgentEntity[] end_getAgents(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __getAgents_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            AgentEntity[] __ret;
            __ret = AgentsListHelper.read(__is);
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    private static final String __getInstanceId_name = "getInstanceId";

    public String getInstanceId()
    {
        return getInstanceId(null, false);
    }

    public String getInstanceId(java.util.Map<String, String> __ctx)
    {
        return getInstanceId(__ctx, true);
    }

    private String getInstanceId(java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "getInstanceId", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("getInstanceId");
                    __delBase = __getDelegate(false);
                    _DiscoverHelloDel __del = (_DiscoverHelloDel)__delBase;
                    return __del.getInstanceId(__ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_getInstanceId()
    {
        return begin_getInstanceId(null, false, null);
    }

    public Ice.AsyncResult begin_getInstanceId(java.util.Map<String, String> __ctx)
    {
        return begin_getInstanceId(__ctx, true, null);
    }

    public Ice.AsyncResult begin_getInstanceId(Ice.Callback __cb)
    {
        return begin_getInstanceId(null, false, __cb);
    }

    public Ice.AsyncResult begin_getInstanceId(java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_getInstanceId(__ctx, true, __cb);
    }

    public Ice.AsyncResult begin_getInstanceId(Callback_DiscoverHello_getInstanceId __cb)
    {
        return begin_getInstanceId(null, false, __cb);
    }

    public Ice.AsyncResult begin_getInstanceId(java.util.Map<String, String> __ctx, Callback_DiscoverHello_getInstanceId __cb)
    {
        return begin_getInstanceId(__ctx, true, __cb);
    }

    private Ice.AsyncResult begin_getInstanceId(java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__getInstanceId_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __getInstanceId_name, __cb);
        try
        {
            __result.__prepare(__getInstanceId_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            __result.__writeEmptyParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public String end_getInstanceId(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __getInstanceId_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            String __ret;
            __ret = __is.readString();
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    public static DiscoverHelloPrx checkedCast(Ice.ObjectPrx __obj)
    {
        DiscoverHelloPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof DiscoverHelloPrx)
            {
                __d = (DiscoverHelloPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    DiscoverHelloPrxHelper __h = new DiscoverHelloPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static DiscoverHelloPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        DiscoverHelloPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof DiscoverHelloPrx)
            {
                __d = (DiscoverHelloPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    DiscoverHelloPrxHelper __h = new DiscoverHelloPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static DiscoverHelloPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        DiscoverHelloPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    DiscoverHelloPrxHelper __h = new DiscoverHelloPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static DiscoverHelloPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        DiscoverHelloPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    DiscoverHelloPrxHelper __h = new DiscoverHelloPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static DiscoverHelloPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        DiscoverHelloPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof DiscoverHelloPrx)
            {
                __d = (DiscoverHelloPrx)__obj;
            }
            else
            {
                DiscoverHelloPrxHelper __h = new DiscoverHelloPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static DiscoverHelloPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        DiscoverHelloPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            DiscoverHelloPrxHelper __h = new DiscoverHelloPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::slices::DiscoverHello"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _DiscoverHelloDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _DiscoverHelloDelD();
    }

    public static void __write(IceInternal.BasicStream __os, DiscoverHelloPrx v)
    {
        __os.writeProxy(v);
    }

    public static DiscoverHelloPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            DiscoverHelloPrxHelper result = new DiscoverHelloPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
