// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `Slices.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package slices;

public interface DiscoverPrx extends Ice.ObjectPrx
{
    public void lookup(DiscoverReplyPrx reply);

    public void lookup(DiscoverReplyPrx reply, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_lookup(DiscoverReplyPrx reply);

    public Ice.AsyncResult begin_lookup(DiscoverReplyPrx reply, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_lookup(DiscoverReplyPrx reply, Ice.Callback __cb);

    public Ice.AsyncResult begin_lookup(DiscoverReplyPrx reply, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_lookup(DiscoverReplyPrx reply, Callback_Discover_lookup __cb);

    public Ice.AsyncResult begin_lookup(DiscoverReplyPrx reply, java.util.Map<String, String> __ctx, Callback_Discover_lookup __cb);

    public void end_lookup(Ice.AsyncResult __result);
}
