// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `Slices.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package slices;

public class Message implements java.lang.Cloneable, java.io.Serializable
{
    public MessageAddress sender;

    public MessageAddress[] receivers;

    public int type;

    public String content;

    public Message()
    {
    }

    public Message(MessageAddress sender, MessageAddress[] receivers, int type, String content)
    {
        this.sender = sender;
        this.receivers = receivers;
        this.type = type;
        this.content = content;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Message _r = null;
        if(rhs instanceof Message)
        {
            _r = (Message)rhs;
        }

        if(_r != null)
        {
            if(sender != _r.sender)
            {
                if(sender == null || _r.sender == null || !sender.equals(_r.sender))
                {
                    return false;
                }
            }
            if(!java.util.Arrays.equals(receivers, _r.receivers))
            {
                return false;
            }
            if(type != _r.type)
            {
                return false;
            }
            if(content != _r.content)
            {
                if(content == null || _r.content == null || !content.equals(_r.content))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::slices::Message");
        __h = IceInternal.HashUtil.hashAdd(__h, sender);
        __h = IceInternal.HashUtil.hashAdd(__h, receivers);
        __h = IceInternal.HashUtil.hashAdd(__h, type);
        __h = IceInternal.HashUtil.hashAdd(__h, content);
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        sender.__write(__os);
        MessageReceiversHelper.write(__os, receivers);
        __os.writeInt(type);
        __os.writeString(content);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        sender = new MessageAddress();
        sender.__read(__is);
        receivers = MessageReceiversHelper.read(__is);
        type = __is.readInt();
        content = __is.readString();
    }

    public static final long serialVersionUID = 1040445619L;
}
