// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `Slices.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package slices;

public final class MessageTransporterPrxHelper extends Ice.ObjectPrxHelperBase implements MessageTransporterPrx
{
    private static final String __transport_name = "transport";

    public void transport(Message data)
    {
        transport(data, null, false);
    }

    public void transport(Message data, java.util.Map<String, String> __ctx)
    {
        transport(data, __ctx, true);
    }

    private void transport(Message data, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "transport", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __delBase = __getDelegate(false);
                    _MessageTransporterDel __del = (_MessageTransporterDel)__delBase;
                    __del.transport(data, __ctx, __observer);
                    return;
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_transport(Message data)
    {
        return begin_transport(data, null, false, null);
    }

    public Ice.AsyncResult begin_transport(Message data, java.util.Map<String, String> __ctx)
    {
        return begin_transport(data, __ctx, true, null);
    }

    public Ice.AsyncResult begin_transport(Message data, Ice.Callback __cb)
    {
        return begin_transport(data, null, false, __cb);
    }

    public Ice.AsyncResult begin_transport(Message data, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_transport(data, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_transport(Message data, Callback_MessageTransporter_transport __cb)
    {
        return begin_transport(data, null, false, __cb);
    }

    public Ice.AsyncResult begin_transport(Message data, java.util.Map<String, String> __ctx, Callback_MessageTransporter_transport __cb)
    {
        return begin_transport(data, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_transport(Message data, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __transport_name, __cb);
        try
        {
            __result.__prepare(__transport_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            data.__write(__os);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public void end_transport(Ice.AsyncResult __result)
    {
        __end(__result, __transport_name);
    }

    public static MessageTransporterPrx checkedCast(Ice.ObjectPrx __obj)
    {
        MessageTransporterPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof MessageTransporterPrx)
            {
                __d = (MessageTransporterPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    MessageTransporterPrxHelper __h = new MessageTransporterPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static MessageTransporterPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        MessageTransporterPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof MessageTransporterPrx)
            {
                __d = (MessageTransporterPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    MessageTransporterPrxHelper __h = new MessageTransporterPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static MessageTransporterPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        MessageTransporterPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    MessageTransporterPrxHelper __h = new MessageTransporterPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static MessageTransporterPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        MessageTransporterPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    MessageTransporterPrxHelper __h = new MessageTransporterPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static MessageTransporterPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        MessageTransporterPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof MessageTransporterPrx)
            {
                __d = (MessageTransporterPrx)__obj;
            }
            else
            {
                MessageTransporterPrxHelper __h = new MessageTransporterPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static MessageTransporterPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        MessageTransporterPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            MessageTransporterPrxHelper __h = new MessageTransporterPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::slices::MessageTransporter"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _MessageTransporterDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _MessageTransporterDelD();
    }

    public static void __write(IceInternal.BasicStream __os, MessageTransporterPrx v)
    {
        __os.writeProxy(v);
    }

    public static MessageTransporterPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            MessageTransporterPrxHelper result = new MessageTransporterPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
