// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `Slices.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package slices;

public interface MessageTransporterPrx extends Ice.ObjectPrx
{
    public void transport(Message data);

    public void transport(Message data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_transport(Message data);

    public Ice.AsyncResult begin_transport(Message data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_transport(Message data, Ice.Callback __cb);

    public Ice.AsyncResult begin_transport(Message data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_transport(Message data, Callback_MessageTransporter_transport __cb);

    public Ice.AsyncResult begin_transport(Message data, java.util.Map<String, String> __ctx, Callback_MessageTransporter_transport __cb);

    public void end_transport(Ice.AsyncResult __result);
}
