// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `Slices.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package slices;

public class MessageAddress implements java.lang.Cloneable, java.io.Serializable
{
    public String id;

    public String container;

    public MessageAddress()
    {
    }

    public MessageAddress(String id, String container)
    {
        this.id = id;
        this.container = container;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        MessageAddress _r = null;
        if(rhs instanceof MessageAddress)
        {
            _r = (MessageAddress)rhs;
        }

        if(_r != null)
        {
            if(id != _r.id)
            {
                if(id == null || _r.id == null || !id.equals(_r.id))
                {
                    return false;
                }
            }
            if(container != _r.container)
            {
                if(container == null || _r.container == null || !container.equals(_r.container))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::slices::MessageAddress");
        __h = IceInternal.HashUtil.hashAdd(__h, id);
        __h = IceInternal.HashUtil.hashAdd(__h, container);
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(id);
        __os.writeString(container);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        id = __is.readString();
        container = __is.readString();
    }

    public static final long serialVersionUID = 917687391L;
}
