// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `Slices.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package slices;

public final class StringsMapHolder
{
    public
    StringsMapHolder()
    {
    }

    public
    StringsMapHolder(java.util.Map<java.lang.String, java.lang.String> value)
    {
        this.value = value;
    }

    public java.util.Map<java.lang.String, java.lang.String> value;
}
