// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `communication.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cz.uhk.fim.ase.communication.impl.internal;

public abstract class Callback_GlobalHelloMessage_getAgents extends Ice.TwowayCallback
{
    public abstract void response(cz.uhk.fim.ase.model.internal.AgentEntity[] __ret);

    public final void __completed(Ice.AsyncResult __result)
    {
        GlobalHelloMessagePrx __proxy = (GlobalHelloMessagePrx)__result.getProxy();
        cz.uhk.fim.ase.model.internal.AgentEntity[] __ret = null;
        try
        {
            __ret = __proxy.end_getAgents(__result);
        }
        catch(Ice.LocalException __ex)
        {
            exception(__ex);
            return;
        }
        response(__ret);
    }
}
