// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `communication.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cz.uhk.fim.ase.communication.impl.internal;

public interface GlobalSyncMessagePrx extends Ice.ObjectPrx
{
    public long getTick();

    public long getTick(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getTick();

    public Ice.AsyncResult begin_getTick(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getTick(Ice.Callback __cb);

    public Ice.AsyncResult begin_getTick(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getTick(Callback_GlobalSyncMessage_getTick __cb);

    public Ice.AsyncResult begin_getTick(java.util.Map<String, String> __ctx, Callback_GlobalSyncMessage_getTick __cb);

    public long end_getTick(Ice.AsyncResult __result);

    public String getId();

    public String getId(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getId();

    public Ice.AsyncResult begin_getId(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getId(Ice.Callback __cb);

    public Ice.AsyncResult begin_getId(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getId(Callback_GlobalSyncMessage_getId __cb);

    public Ice.AsyncResult begin_getId(java.util.Map<String, String> __ctx, Callback_GlobalSyncMessage_getId __cb);

    public String end_getId(Ice.AsyncResult __result);
}
