// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `communication.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cz.uhk.fim.ase.communication.impl.internal;

public final class GlobalSyncMessagePrxHelper extends Ice.ObjectPrxHelperBase implements GlobalSyncMessagePrx
{
    private static final String __getId_name = "getId";

    public String getId()
    {
        return getId(null, false);
    }

    public String getId(java.util.Map<String, String> __ctx)
    {
        return getId(__ctx, true);
    }

    private String getId(java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "getId", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("getId");
                    __delBase = __getDelegate(false);
                    _GlobalSyncMessageDel __del = (_GlobalSyncMessageDel)__delBase;
                    return __del.getId(__ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_getId()
    {
        return begin_getId(null, false, null);
    }

    public Ice.AsyncResult begin_getId(java.util.Map<String, String> __ctx)
    {
        return begin_getId(__ctx, true, null);
    }

    public Ice.AsyncResult begin_getId(Ice.Callback __cb)
    {
        return begin_getId(null, false, __cb);
    }

    public Ice.AsyncResult begin_getId(java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_getId(__ctx, true, __cb);
    }

    public Ice.AsyncResult begin_getId(Callback_GlobalSyncMessage_getId __cb)
    {
        return begin_getId(null, false, __cb);
    }

    public Ice.AsyncResult begin_getId(java.util.Map<String, String> __ctx, Callback_GlobalSyncMessage_getId __cb)
    {
        return begin_getId(__ctx, true, __cb);
    }

    private Ice.AsyncResult begin_getId(java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__getId_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __getId_name, __cb);
        try
        {
            __result.__prepare(__getId_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            __result.__writeEmptyParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public String end_getId(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __getId_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            String __ret;
            __ret = __is.readString();
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    private static final String __getTick_name = "getTick";

    public long getTick()
    {
        return getTick(null, false);
    }

    public long getTick(java.util.Map<String, String> __ctx)
    {
        return getTick(__ctx, true);
    }

    private long getTick(java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "getTick", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("getTick");
                    __delBase = __getDelegate(false);
                    _GlobalSyncMessageDel __del = (_GlobalSyncMessageDel)__delBase;
                    return __del.getTick(__ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_getTick()
    {
        return begin_getTick(null, false, null);
    }

    public Ice.AsyncResult begin_getTick(java.util.Map<String, String> __ctx)
    {
        return begin_getTick(__ctx, true, null);
    }

    public Ice.AsyncResult begin_getTick(Ice.Callback __cb)
    {
        return begin_getTick(null, false, __cb);
    }

    public Ice.AsyncResult begin_getTick(java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_getTick(__ctx, true, __cb);
    }

    public Ice.AsyncResult begin_getTick(Callback_GlobalSyncMessage_getTick __cb)
    {
        return begin_getTick(null, false, __cb);
    }

    public Ice.AsyncResult begin_getTick(java.util.Map<String, String> __ctx, Callback_GlobalSyncMessage_getTick __cb)
    {
        return begin_getTick(__ctx, true, __cb);
    }

    private Ice.AsyncResult begin_getTick(java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__getTick_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __getTick_name, __cb);
        try
        {
            __result.__prepare(__getTick_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            __result.__writeEmptyParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public long end_getTick(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __getTick_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            long __ret;
            __ret = __is.readLong();
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    public static GlobalSyncMessagePrx checkedCast(Ice.ObjectPrx __obj)
    {
        GlobalSyncMessagePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof GlobalSyncMessagePrx)
            {
                __d = (GlobalSyncMessagePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    GlobalSyncMessagePrxHelper __h = new GlobalSyncMessagePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static GlobalSyncMessagePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        GlobalSyncMessagePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof GlobalSyncMessagePrx)
            {
                __d = (GlobalSyncMessagePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    GlobalSyncMessagePrxHelper __h = new GlobalSyncMessagePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static GlobalSyncMessagePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        GlobalSyncMessagePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    GlobalSyncMessagePrxHelper __h = new GlobalSyncMessagePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static GlobalSyncMessagePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        GlobalSyncMessagePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    GlobalSyncMessagePrxHelper __h = new GlobalSyncMessagePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static GlobalSyncMessagePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        GlobalSyncMessagePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof GlobalSyncMessagePrx)
            {
                __d = (GlobalSyncMessagePrx)__obj;
            }
            else
            {
                GlobalSyncMessagePrxHelper __h = new GlobalSyncMessagePrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static GlobalSyncMessagePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        GlobalSyncMessagePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            GlobalSyncMessagePrxHelper __h = new GlobalSyncMessagePrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::internal::GlobalSyncMessage"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _GlobalSyncMessageDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _GlobalSyncMessageDelD();
    }

    public static void __write(IceInternal.BasicStream __os, GlobalSyncMessagePrx v)
    {
        __os.writeProxy(v);
    }

    public static GlobalSyncMessagePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            GlobalSyncMessagePrxHelper result = new GlobalSyncMessagePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
