// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `communication.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cz.uhk.fim.ase.communication.impl.internal;

public interface GlobalHandlerPrx extends Ice.ObjectPrx
{
    public void lookup(GlobalReplyPrx reply);

    public void lookup(GlobalReplyPrx reply, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_lookup(GlobalReplyPrx reply);

    public Ice.AsyncResult begin_lookup(GlobalReplyPrx reply, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_lookup(GlobalReplyPrx reply, Ice.Callback __cb);

    public Ice.AsyncResult begin_lookup(GlobalReplyPrx reply, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_lookup(GlobalReplyPrx reply, Callback_GlobalHandler_lookup __cb);

    public Ice.AsyncResult begin_lookup(GlobalReplyPrx reply, java.util.Map<String, String> __ctx, Callback_GlobalHandler_lookup __cb);

    public void end_lookup(Ice.AsyncResult __result);
}
