// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `communication.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cz.uhk.fim.ase.communication.impl.internal;

public final class GlobalReplyPrxHelper extends Ice.ObjectPrxHelperBase implements GlobalReplyPrx
{
    private static final String __reply_name = "reply";

    public void reply(Ice.ObjectPrx obj)
    {
        reply(obj, null, false);
    }

    public void reply(Ice.ObjectPrx obj, java.util.Map<String, String> __ctx)
    {
        reply(obj, __ctx, true);
    }

    private void reply(Ice.ObjectPrx obj, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "reply", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __delBase = __getDelegate(false);
                    _GlobalReplyDel __del = (_GlobalReplyDel)__delBase;
                    __del.reply(obj, __ctx, __observer);
                    return;
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_reply(Ice.ObjectPrx obj)
    {
        return begin_reply(obj, null, false, null);
    }

    public Ice.AsyncResult begin_reply(Ice.ObjectPrx obj, java.util.Map<String, String> __ctx)
    {
        return begin_reply(obj, __ctx, true, null);
    }

    public Ice.AsyncResult begin_reply(Ice.ObjectPrx obj, Ice.Callback __cb)
    {
        return begin_reply(obj, null, false, __cb);
    }

    public Ice.AsyncResult begin_reply(Ice.ObjectPrx obj, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_reply(obj, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_reply(Ice.ObjectPrx obj, Callback_GlobalReply_reply __cb)
    {
        return begin_reply(obj, null, false, __cb);
    }

    public Ice.AsyncResult begin_reply(Ice.ObjectPrx obj, java.util.Map<String, String> __ctx, Callback_GlobalReply_reply __cb)
    {
        return begin_reply(obj, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_reply(Ice.ObjectPrx obj, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __reply_name, __cb);
        try
        {
            __result.__prepare(__reply_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeProxy(obj);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public void end_reply(Ice.AsyncResult __result)
    {
        __end(__result, __reply_name);
    }

    public static GlobalReplyPrx checkedCast(Ice.ObjectPrx __obj)
    {
        GlobalReplyPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof GlobalReplyPrx)
            {
                __d = (GlobalReplyPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    GlobalReplyPrxHelper __h = new GlobalReplyPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static GlobalReplyPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        GlobalReplyPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof GlobalReplyPrx)
            {
                __d = (GlobalReplyPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    GlobalReplyPrxHelper __h = new GlobalReplyPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static GlobalReplyPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        GlobalReplyPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    GlobalReplyPrxHelper __h = new GlobalReplyPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static GlobalReplyPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        GlobalReplyPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    GlobalReplyPrxHelper __h = new GlobalReplyPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static GlobalReplyPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        GlobalReplyPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof GlobalReplyPrx)
            {
                __d = (GlobalReplyPrx)__obj;
            }
            else
            {
                GlobalReplyPrxHelper __h = new GlobalReplyPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static GlobalReplyPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        GlobalReplyPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            GlobalReplyPrxHelper __h = new GlobalReplyPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::internal::GlobalReply"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _GlobalReplyDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _GlobalReplyDelD();
    }

    public static void __write(IceInternal.BasicStream __os, GlobalReplyPrx v)
    {
        __os.writeProxy(v);
    }

    public static GlobalReplyPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            GlobalReplyPrxHelper result = new GlobalReplyPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
