// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `communication.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cz.uhk.fim.ase.communication.impl.internal;

public final class MessagesHandlerPrxHelper extends Ice.ObjectPrxHelperBase implements MessagesHandlerPrx
{
    private static final String __handle_name = "handle";

    public void handle(cz.uhk.fim.ase.model.internal.MessageEntity message)
    {
        handle(message, null, false);
    }

    public void handle(cz.uhk.fim.ase.model.internal.MessageEntity message, java.util.Map<String, String> __ctx)
    {
        handle(message, __ctx, true);
    }

    private void handle(cz.uhk.fim.ase.model.internal.MessageEntity message, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "handle", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __delBase = __getDelegate(false);
                    _MessagesHandlerDel __del = (_MessagesHandlerDel)__delBase;
                    __del.handle(message, __ctx, __observer);
                    return;
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_handle(cz.uhk.fim.ase.model.internal.MessageEntity message)
    {
        return begin_handle(message, null, false, null);
    }

    public Ice.AsyncResult begin_handle(cz.uhk.fim.ase.model.internal.MessageEntity message, java.util.Map<String, String> __ctx)
    {
        return begin_handle(message, __ctx, true, null);
    }

    public Ice.AsyncResult begin_handle(cz.uhk.fim.ase.model.internal.MessageEntity message, Ice.Callback __cb)
    {
        return begin_handle(message, null, false, __cb);
    }

    public Ice.AsyncResult begin_handle(cz.uhk.fim.ase.model.internal.MessageEntity message, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_handle(message, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_handle(cz.uhk.fim.ase.model.internal.MessageEntity message, Callback_MessagesHandler_handle __cb)
    {
        return begin_handle(message, null, false, __cb);
    }

    public Ice.AsyncResult begin_handle(cz.uhk.fim.ase.model.internal.MessageEntity message, java.util.Map<String, String> __ctx, Callback_MessagesHandler_handle __cb)
    {
        return begin_handle(message, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_handle(cz.uhk.fim.ase.model.internal.MessageEntity message, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __handle_name, __cb);
        try
        {
            __result.__prepare(__handle_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            message.__write(__os);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public void end_handle(Ice.AsyncResult __result)
    {
        __end(__result, __handle_name);
    }

    public static MessagesHandlerPrx checkedCast(Ice.ObjectPrx __obj)
    {
        MessagesHandlerPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof MessagesHandlerPrx)
            {
                __d = (MessagesHandlerPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    MessagesHandlerPrxHelper __h = new MessagesHandlerPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static MessagesHandlerPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        MessagesHandlerPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof MessagesHandlerPrx)
            {
                __d = (MessagesHandlerPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    MessagesHandlerPrxHelper __h = new MessagesHandlerPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static MessagesHandlerPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        MessagesHandlerPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    MessagesHandlerPrxHelper __h = new MessagesHandlerPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static MessagesHandlerPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        MessagesHandlerPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    MessagesHandlerPrxHelper __h = new MessagesHandlerPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static MessagesHandlerPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        MessagesHandlerPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof MessagesHandlerPrx)
            {
                __d = (MessagesHandlerPrx)__obj;
            }
            else
            {
                MessagesHandlerPrxHelper __h = new MessagesHandlerPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static MessagesHandlerPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        MessagesHandlerPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            MessagesHandlerPrxHelper __h = new MessagesHandlerPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::internal::MessagesHandler"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _MessagesHandlerDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _MessagesHandlerDelD();
    }

    public static void __write(IceInternal.BasicStream __os, MessagesHandlerPrx v)
    {
        __os.writeProxy(v);
    }

    public static MessagesHandlerPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            MessagesHandlerPrxHelper result = new MessagesHandlerPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
