// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `communication.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cz.uhk.fim.ase.communication.impl.internal;

public interface MessagesHandlerPrx extends Ice.ObjectPrx
{
    public void handle(cz.uhk.fim.ase.model.internal.MessageEntity message);

    public void handle(cz.uhk.fim.ase.model.internal.MessageEntity message, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_handle(cz.uhk.fim.ase.model.internal.MessageEntity message);

    public Ice.AsyncResult begin_handle(cz.uhk.fim.ase.model.internal.MessageEntity message, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_handle(cz.uhk.fim.ase.model.internal.MessageEntity message, Ice.Callback __cb);

    public Ice.AsyncResult begin_handle(cz.uhk.fim.ase.model.internal.MessageEntity message, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_handle(cz.uhk.fim.ase.model.internal.MessageEntity message, Callback_MessagesHandler_handle __cb);

    public Ice.AsyncResult begin_handle(cz.uhk.fim.ase.model.internal.MessageEntity message, java.util.Map<String, String> __ctx, Callback_MessagesHandler_handle __cb);

    public void end_handle(Ice.AsyncResult __result);
}
