// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `model.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cz.uhk.fim.ase.model.internal;

public class AgentEntity implements java.lang.Cloneable, java.io.Serializable
{
    public String container;

    public String id;

    public java.util.Map<java.lang.String, java.lang.String> properties;

    public AgentEntity()
    {
    }

    public AgentEntity(String container, String id, java.util.Map<java.lang.String, java.lang.String> properties)
    {
        this.container = container;
        this.id = id;
        this.properties = properties;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        AgentEntity _r = null;
        if(rhs instanceof AgentEntity)
        {
            _r = (AgentEntity)rhs;
        }

        if(_r != null)
        {
            if(container != _r.container)
            {
                if(container == null || _r.container == null || !container.equals(_r.container))
                {
                    return false;
                }
            }
            if(id != _r.id)
            {
                if(id == null || _r.id == null || !id.equals(_r.id))
                {
                    return false;
                }
            }
            if(properties != _r.properties)
            {
                if(properties == null || _r.properties == null || !properties.equals(_r.properties))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::internal::AgentEntity");
        __h = IceInternal.HashUtil.hashAdd(__h, container);
        __h = IceInternal.HashUtil.hashAdd(__h, id);
        __h = IceInternal.HashUtil.hashAdd(__h, properties);
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(container);
        __os.writeString(id);
        StringsMapHelper.write(__os, properties);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        container = __is.readString();
        id = __is.readString();
        properties = StringsMapHelper.read(__is);
    }

    public static final long serialVersionUID = 1430305986L;
}
