// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `model.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cz.uhk.fim.ase.model.internal;

public final class AgentsListHolder
{
    public
    AgentsListHolder()
    {
    }

    public
    AgentsListHolder(AgentEntity[] value)
    {
        this.value = value;
    }

    public AgentEntity[] value;
}
